
-- =============== SUPPORT TICKETS ===============
CREATE TABLE public.support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  email text,
  subject text NOT NULL,
  body text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'open',
  priority text NOT NULL DEFAULT 'normal',
  category text NOT NULL DEFAULT 'general',
  source text NOT NULL DEFAULT 'user',
  assigned_to uuid,
  conversation_id uuid,
  resolution_note text,
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  unread_admin_count integer NOT NULL DEFAULT 0,
  unread_user_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT support_tickets_status_check CHECK (status IN ('open','pending','resolved','closed')),
  CONSTRAINT support_tickets_priority_check CHECK (priority IN ('low','normal','high','urgent')),
  CONSTRAINT support_tickets_source_check CHECK (source IN ('user','ai_escalation','human_request','contact_form','admin'))
);
CREATE UNIQUE INDEX support_tickets_number_key ON public.support_tickets(ticket_number);
CREATE INDEX support_tickets_user_idx ON public.support_tickets(user_id, created_at DESC);
CREATE INDEX support_tickets_status_idx ON public.support_tickets(status, last_activity_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.support_tickets TO authenticated;
GRANT ALL ON public.support_tickets TO service_role;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own tickets" ON public.support_tickets
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[]));

CREATE POLICY "Users create own tickets" ON public.support_tickets
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND status = 'open'
    AND assigned_to IS NULL
    AND resolution_note IS NULL
  );

CREATE POLICY "Staff manage tickets" ON public.support_tickets
  FOR UPDATE TO authenticated
  USING (public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[]))
  WITH CHECK (public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[]));

CREATE POLICY "Staff delete tickets" ON public.support_tickets
  FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

GRANT DELETE ON public.support_tickets TO authenticated;

-- =============== TICKET MESSAGES ===============
CREATE TABLE public.support_ticket_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  sender_id uuid,
  sender_role text NOT NULL DEFAULT 'user',
  content text NOT NULL,
  is_internal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT support_ticket_messages_role_check CHECK (sender_role IN ('user','admin','ai','system'))
);
CREATE INDEX support_ticket_messages_ticket_idx ON public.support_ticket_messages(ticket_id, created_at);

GRANT SELECT, INSERT ON public.support_ticket_messages TO authenticated;
GRANT ALL ON public.support_ticket_messages TO service_role;
ALTER TABLE public.support_ticket_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "View ticket messages" ON public.support_ticket_messages
  FOR SELECT TO authenticated
  USING (
    public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[])
    OR (
      is_internal = false
      AND EXISTS (SELECT 1 FROM public.support_tickets t WHERE t.id = ticket_id AND t.user_id = auth.uid())
    )
  );

CREATE POLICY "Reply to ticket" ON public.support_ticket_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND (
      (public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[]) AND sender_role = 'admin')
      OR (
        sender_role = 'user'
        AND is_internal = false
        AND EXISTS (SELECT 1 FROM public.support_tickets t WHERE t.id = ticket_id AND t.user_id = auth.uid())
      )
    )
  );

-- keep ticket activity + unread counters in sync
CREATE OR REPLACE FUNCTION public.touch_support_ticket_on_message()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.support_tickets
  SET last_activity_at = now(),
      updated_at = now(),
      unread_admin_count = CASE WHEN NEW.sender_role = 'user' THEN unread_admin_count + 1 ELSE unread_admin_count END,
      unread_user_count = CASE WHEN NEW.sender_role = 'admin' AND NEW.is_internal = false THEN unread_user_count + 1 ELSE unread_user_count END,
      status = CASE
        WHEN NEW.sender_role = 'user' AND status IN ('resolved','closed') THEN 'open'
        WHEN NEW.sender_role = 'admin' AND status = 'open' THEN 'pending'
        ELSE status END
  WHERE id = NEW.ticket_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_touch_support_ticket
AFTER INSERT ON public.support_ticket_messages
FOR EACH ROW EXECUTE FUNCTION public.touch_support_ticket_on_message();

CREATE TRIGGER trg_support_tickets_updated_at
BEFORE UPDATE ON public.support_tickets
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- users may not tamper with staff-only fields on their own tickets
CREATE OR REPLACE FUNCTION public.enforce_ticket_owner_update_scope()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.has_any_role(auth.uid(), ARRAY['admin','moderator','support']::app_role[]) THEN
    RETURN NEW;
  END IF;
  NEW.assigned_to := OLD.assigned_to;
  NEW.priority := OLD.priority;
  NEW.resolution_note := OLD.resolution_note;
  NEW.ticket_number := OLD.ticket_number;
  NEW.user_id := OLD.user_id;
  NEW.source := OLD.source;
  NEW.unread_admin_count := OLD.unread_admin_count;
  IF NEW.status IS DISTINCT FROM OLD.status AND NEW.status NOT IN ('open','closed') THEN
    NEW.status := OLD.status;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_enforce_ticket_owner_update_scope
BEFORE UPDATE ON public.support_tickets
FOR EACH ROW EXECUTE FUNCTION public.enforce_ticket_owner_update_scope();

CREATE POLICY "Users update own tickets" ON public.support_tickets
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- =============== AUTOMATION EVENTS (idempotent milestone emails) ===============
CREATE TABLE public.automation_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  automation_key text NOT NULL,
  ref_id text,
  dedupe_key text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  error text,
  processed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT automation_events_status_check CHECK (status IN ('pending','sent','skipped','failed'))
);
CREATE UNIQUE INDEX automation_events_dedupe_key ON public.automation_events(dedupe_key);
CREATE INDEX automation_events_pending_idx ON public.automation_events(status, created_at);

GRANT SELECT ON public.automation_events TO authenticated;
GRANT ALL ON public.automation_events TO service_role;
ALTER TABLE public.automation_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins view automation events" ON public.automation_events
  FOR SELECT TO authenticated
  USING (public.has_any_role(auth.uid(), ARRAY['admin','moderator']::app_role[]));

-- queue helper used by triggers
CREATE OR REPLACE FUNCTION public.queue_automation(_user_id uuid, _key text, _ref text, _payload jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.automation_events (user_id, automation_key, ref_id, dedupe_key, payload)
  VALUES (_user_id, _key, _ref, _key || ':' || coalesce(_user_id::text,'anon') || ':' || coalesce(_ref,'-'), coalesce(_payload,'{}'::jsonb))
  ON CONFLICT (dedupe_key) DO NOTHING;
END;
$$;

-- milestone triggers
CREATE OR REPLACE FUNCTION public.automation_on_enrollment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.queue_automation(NEW.user_id, 'enrollment_confirmed', NEW.course_id::text, jsonb_build_object('course_id', NEW.course_id));
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_automation_on_enrollment
AFTER INSERT ON public.enrollments
FOR EACH ROW EXECUTE FUNCTION public.automation_on_enrollment();

CREATE OR REPLACE FUNCTION public.automation_on_lesson_progress()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.completed = true AND (TG_OP = 'INSERT' OR OLD.completed IS DISTINCT FROM true) THEN
    PERFORM public.queue_automation(NEW.user_id, 'first_lesson_completed', NULL, jsonb_build_object('lesson_id', NEW.lesson_id));
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_automation_on_lesson_progress
AFTER INSERT OR UPDATE ON public.lesson_progress
FOR EACH ROW EXECUTE FUNCTION public.automation_on_lesson_progress();

CREATE OR REPLACE FUNCTION public.automation_on_certificate()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.queue_automation(NEW.user_id, 'certificate_ready', NEW.id::text, jsonb_build_object('certificate_id', NEW.id, 'course_id', NEW.course_id, 'verification_code', NEW.verification_code));
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_automation_on_certificate
AFTER INSERT ON public.certificates
FOR EACH ROW EXECUTE FUNCTION public.automation_on_certificate();

CREATE OR REPLACE FUNCTION public.automation_on_cohort_member()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  PERFORM public.queue_automation(NEW.user_id, 'cohort_access_granted', NEW.cohort_id::text, jsonb_build_object('cohort_id', NEW.cohort_id));
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_automation_on_cohort_member
AFTER INSERT ON public.cohort_members
FOR EACH ROW EXECUTE FUNCTION public.automation_on_cohort_member();

CREATE OR REPLACE FUNCTION public.automation_on_submission_grade()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.queue_automation(NEW.user_id, 'first_assignment_submitted', NULL, jsonb_build_object('assignment_id', NEW.assignment_id));
  ELSIF NEW.grade IS NOT NULL AND OLD.grade IS DISTINCT FROM NEW.grade THEN
    PERFORM public.queue_automation(NEW.user_id, 'assignment_graded', NEW.id::text, jsonb_build_object('assignment_id', NEW.assignment_id, 'grade', NEW.grade));
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_automation_on_submission_grade
AFTER INSERT OR UPDATE ON public.assignment_submissions
FOR EACH ROW EXECUTE FUNCTION public.automation_on_submission_grade();
